app/tasks/forms.py
#forms.py - help forms handing and data validation
#/app/tasks/forms.py

from wtforms import Form, TextField, DateField, IntegerField, \
                        SelectField, PasswordField, validators
                            
class AddTask(Form):
    task_id = IntegerField('Priority')
    name = TextField('Task Name', [validators.Required()])
    due_date = DateField('Date Due (mm/dd/yyyy)', [validators.Required()],
                            format = '%m/%d/%Y')
    priority = SelectField('Priority', [validators.Required()],choices=[('1','1'),
                            ('2','2'),('3','3'),('4','4'),('5','5'),('6','6'),
                            ('7','7'),('8','8'),('9','9'),('10','10')])
    posted_date = DateField('Posted Date (mm/dd/yyyy)', [validators.Required()], format='%m/%d/%Y')
    status = IntegerField('Status')

    

app/tasks/__init__.py
#

app/tasks/views.py
#views.py
#/app/tasks/views.py

from app import app, db
from flask import Blueprint, flash, redirect, render_template, request, \
                    session, url_for
from app.views import login_required, flash_errors
from forms import AddTask
from app.models import FTasks

mod = Blueprint('tasks',__name__, url_prefix='/tasks',template_folder='templates',
                static_folder = 'static')




#Task fetch all from db    
@mod.route('/tasks/')
@login_required
def tasks():
    open_tasks = db.session.query(FTasks).filter_by(status='1').order_by(FTasks.due_date.asc())
    closed_tasks = db.session.query(FTasks).filter_by(status='0').order_by(FTasks.due_date.asc())
    return render_template('/tasks.html',form = AddTask(request.form),
            open_tasks=open_tasks, closed_tasks = closed_tasks)


#Add new tasks:
@mod.route('/add/',methods=['POST','GET'])
@login_required
def new_task():
    form = AddTask(request.form)
    if form.validate():
        new_task = FTasks(
                    form.name.data,
                    form.due_date.data,
                    form.priority.data,
                    form.posted_date.data,
                    '1',
                    session['user_id']
                    )
        db.session.add(new_task)
        db.session.commit()
        flash('New entry was successfully posted. Thanks.')
    else:
        flash_errors(form)
    return redirect(url_for('.tasks'))

        
#Mark tasks as complete:
@mod.route('/complete/<int:task_id>/',)
@login_required
def complete(task_id):
    new_id = task_id
    db.session.query(FTasks).filter_by(task_id=new_id).update({"status":"0"})
    db.session.commit()
    flash('The task was marked as complete. Nice.')
    return redirect(url_for('.tasks'))
    

#Delete Tasks:
@mod.route('/delete/<int:task_id>/',)
@login_required
def delete_entry(task_id):
    new_id = task_id
    db.session.query(FTasks).filter_by(task_id=new_id).delete()
    db.session.commit()
    flash('The task was deleted. Why not add a new one?')
    return redirect(url_for('.tasks'))

    
#Incomplete the closed tasks:
@mod.route('/incomplete/<int:task_id>/',)
@login_required
def uncomplete(task_id):
    new_id = task_id
    db.session.query(FTasks).filter_by(task_id=new_id).update({'status':'1'})
    db.session.commit()
    flash('The task was marked as incomplete.')
    return redirect(url_for('.tasks'))
    
    

    
    

app/tasks/templates/tasks.html
{% extends "template.html" %}
{% block content %}
  <h1>Welcome to FlaskTaskR</h1>
  <br/>
  <a href="{{url_for('users.logout')}}">Logout</a>
  <div class="add-task">
    <h3>Add a new task:</h3>
      <form method="POST" action="{{url_for('tasks.new_task')}}">
        <table>
          <tr>
            <td>{{form.name.label}}{{form.name}}&nbsp;</td>
            <td>{{form.due_date.label}}{{form.due_date}}</td>
          </tr>
          <tr>
            <td>{{form.posted_date.label}}{{form.posted_date}}</td>
            <td>{{form.priority.label}}{{form.priority}}</td>
          </tr>
       </table>
      <p><input type="submit" value="Submit" class="btn-primary"></p>
      </form>
  </div>
  <div class="entries">
    <br/>
    <br/>
    <h2>Open tasks:</h2>
    <div class="datagrid">
      <table>
        <thead>
        <tr>
        <th width="200px"><strong>Task Name</strong></th>
        <th width="80px"><strong>Due Date</strong></th>
        <th width="90px"><strong>Posted Date</strong></th>
        <th width="50px"><strong>Priority</strong></th>
        <th width="90px"><strong>Posted By</strong></th>
        <th width="50px"><strong>Delete</strong></th>
        <th width="100px"><strong>Complete?</strong></th>
        </tr>
        </thead>
        {% for o in open_tasks %}
        <tr>
          <tbody>
        <td width="200px">{{o.name}}</td>
        <td width="80px">{{o.due_date}}</td>
        <td width="90px">{{o.posted_date}}</td>
        <td width="50px">{{o.priority}}</td>
        <td width="90px">{{o.poster.name}}</td>
        <td width="50px"><a href="{{url_for('tasks.delete_entry',task_id=o.task_id)}}">Delete</a></td>
         <td width="100px"><a href="{{url_for('tasks.complete',task_id=o.task_id)}}">Mark as Complete</a></td>
       </tbody>
        </tr>
        {% endfor%}
      </table>
    </div>
  </div>
  
    <br/>
    <br/>
    <h2>Closed tasks:</h2>
    <div class="datagrid">
    <table>
      <thead>
      <tr>
      <th width="200px"><strong>Task Name</strong></th>
      <th width="80px"><strong>Due Date</strong></th>
      <th width="90px"><strong>Posted Date</strong></th>
      <th width="50px"><strong>Priority</strong></th>
      <th width="90px"><strong>Posted By</strong></th>
      <th width="50px"><strong>Delete</strong></th>
      <th width="100px"><strong>Incomplete?</strong></th>
      </tr>
      </thead>
      {% for c in closed_tasks %}
      <tr>
      <td width="200px">{{c.name}}</td>
      <td width="80px">{{c.due_date}}</td>
      <td width="90px">{{c.posted_date}}</td>
      <td width="50px">{{c.priority}}</td>
      <td width="90px">{{c.poster.name}}</td>
      <td width="50px"><a href="{{url_for('tasks.delete_entry',task_id=c.task_id)}}">Delete</a></td>
      <td width="100px"><a href="{{url_for('tasks.uncomplete', task_id=c.task_id)}}">Cancel</a></td>
      </tr>
      {% endfor%}
    </table>
    </div>
{%endblock%}
    

app/tasks/templates/template.html
<!-- /app/tasks/templates/tempalte.html -->
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Welcome to FlaskTaskr!!</title>
    <link rel="stylesheet" href="{{url_for('tasks.static',filename='bootstrap.css')}}">
  </head>
  <body>
    <div class="page">
      {% for message in get_flashed_messages() %}
        <div class="flash">{{message}}</div>
          <br/>
        {%endfor%}
      {%if error%}
        <p class="error"><strong>Error:</strong>{{error}}
      {%endif%}
      {%block content%}
      {%endblock%}
    </div>
  </body>
</html>