app/users/forms.py
#forms.py - help forms handing and data validation

from wtforms import Form, TextField, DateField, IntegerField, \
                        SelectField, PasswordField, validators
                            
    
class RegisterForm(Form):
    name = TextField('Username', [validators.Required(), validators.Length(min=4,max=25)])
    email= TextField('Email', [validators.Required(), validators.Length(min=4,max=40)])
    password = PasswordField('Password',[validators.Required(),validators.Length(min=4,max=40),
                                validators.EqualTo('confirm', message='Passwords must match')])
    confirm = PasswordField('Repeat Password',[validators.Required(),validators.Length(min=4,max=40)])
    

class LoginForm(Form):
    name = TextField('Username', [validators.Required()])
    password = PasswordField('Password', [validators.Required()])
    

app/users/__init__.py
#

app/users/views.py
#views.py
#/app/users/views.py

from app import db
from flask import Blueprint, flash, redirect, render_template, request, \
                    session, url_for
from app.views import login_required, flash_errors
from forms import  RegisterForm, LoginForm
from app.models import User
from sqlalchemy.exc import IntegrityError

mod = Blueprint('users',__name__, url_prefix='/users', 
                template_folder='templates', static_folder='static')


#logout    
@mod.route('/logout/')
def logout():
    session.pop('logged_in',None)
    session.pop('user_id',None)
    flash('You are logged out. Bye. :(')
    return redirect (url_for('users.login'))

    
#main login    
@mod.route('/',methods=['POST','GET'])
def login():
    error = None
    form = LoginForm(request.form)
    if request.method =="POST" and form.validate():
        name = form.name.data
        password = form.password.data
        #u = User.query.filter_by(name=name,password=password).first()
        u = db.session.query(User).filter_by(name=name,password=password).first()
        if u is None:
            error = 'Invalid Credentials. Please try again.'
        else:
            session['logged_in'] = True
            session['user_id'] = u.id
            flash('You are logged in. Go Crazy.')
            return redirect(url_for('tasks.tasks'))
    return render_template('/login.html', form=LoginForm(request.form),error=error)
    
#for new user to register
@mod.route('/register/', methods=['GET','POST'])
def register():
    error = None
    form = RegisterForm(request.form)
    if form.validate():
        new_user = User(
                form.name.data,
                form.email.data,
                form.password.data,
                )
        try:
            db.session.add(new_user)
            db.session.commit()
            flash('Thanks for registering. Please login.')
            return redirect(url_for('.login'))
        except IntegrityError:
            error = 'Oh no! That username and/or email already exist. Please try again.'
    else:
        if request.method == "POST" :
            flash_errors(form)    
    return render_template('/register.html', form = form, error=error)
    
    
    

app/users/templates/login.html
{% extends "template.html" %}
{% block content%}
  <h1>Welcome to FlaskTaskr.</h1>
  <h3>Please login to access your task list.</h3>
  <form method="POST" action="">
  	{{form.name.label}}{{ form.name}}
  	{{form.password.label}}{{ form.password}}
  	<p><input type="submit" value="Submit" class="btn-primary"></p>
  </form>
  <p><em>Need an account?</em><a href="{{url_for('users.register')}}">Sign up!!</a></p>
{%endblock%}

app/users/templates/register.html
{% extends "template.html" %}
{% block content %}
  <h1>Welcome to FlaskTaskr.</h1>
  <h3>Please register to access the task list.</h3>
    <form method="POST" action="">
    	<table>
    		<tr>
    			<td>{{ form.name.label }}{{ form.name }}</td>
    			<td>{{ form.email.label }} {{ form.email }}</td>
    		</tr>
    		<tr>
    			<td>{{ form.password.label }}{{ form.password }}</td>
    			<td>{{ form.confirm.label }}{{ form.confirm }}</td>
    		</tr>
    	</table>
      <p><input type="submit" value="Register" class="btn-primary"></p>
    </form>
    <p><em>Already registered?</em> Click <a href="{{url_for('users.login')}}">here</a> to login.</p>
{% endblock %}

app/users/templates/template.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Welcome to FlaskTaskr!!</title>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="">
    <meta charset="utf-8">
    <link href="{{url_for('users.static',filename='bootstap.css')}}" ref="stylesheet">
    <!-- <link rel="stylesheet" href="{{url_for('static',filename='styles.css')}}"> -->
    <style>body{padding-top:65px;}</style>
  </head>
  <body>
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="/">FlaskTaskr</a>
        <div class="nav-collapse">
          <ul class="nav">
          </ul>
          <ul class="nav pull-right">
            {% if not session.logged_in %}
              <li><a href="{{url_for('users.register')}}">Signup</a></li>
              {% else %}
              <li><a href="{{url_for('users.logout')}}">Logout</a></li>
            {% endif %}
          </ul>
        </div>
      </div>
    </div>
    <div class="new">
      <div class="content">
        {% for message in get_flashed_messages() %}
          <div class=flash>{{message}}</div>
            <br/>
          {%endfor%}
        {%if error%}
          <p class=error><strong>Error:</strong>{{error}}
        {%endif%}
        {%block content%}
        {%endblock%}
      </div>
    </div>
    <footer class="footer">
      <hr>
      <p>&copy; FlaskTaskr</p>
    </footer>
  </body>
</html>